Circuit oram/dependency inject evictor
wjuan-mob/mc-oblivious pull request #7
Opened 2022-07-29 17:33 UTC by wjuan-mob

The motivation for this PR is to let Path_oram use multiple different kinds of evictors. 

This PR: 

- Refactors path_oram to take in an evictor factory, and adds 2 kinds of path oram evictor using different branch selection strategies. The functionality in this case should be the same as preexisting code, because the evictors created do not evict any additional branches and only pack the stash into the already checked out branch, as in the current code. 
- Updates associated Oram_creators in path_oram/lib.rs and no_asm crate. 
- Adds a function that iterates over branches reverse lexicographically and associated tests

2022-08-08 18:56 UTC, garbageslam approved these changes
thank you !

2022-08-22 16:23 UTC, nick-mobilecoin requested changes
I think either my understanding of how `height` is computed needs to be clarified or there needs to be a documented follow on issue/PR to fix the usage of the term so that it's consistent with tree terminology.  Not saying this PR should address the problem, just want to see it planned for.

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +use rand_core::RngCore;
:upside_down_face: 
I wouldn't suggest as part of this PR, but the newlines between all of the use statements is preventing cargo fmt from consolidating
```suggestion
use rand_core::{CryptoRng, RngCore};

use crate::path_oram::{BranchCheckout, MetaSize};
```

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +/// Selects branches in reverse lexicographic order. Num_bits_needed corresponds
:upside_down_face: 
```suggestion
/// Selects branches in reverse lexicographic order. `num_bits_needed` corresponds
```

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +mod internal_tests {
:upside_down_face: 
It seems that most rust code uses `mod tests` when there is only one test group inside of a file.
```suggestion
mod tests {
```

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +    fn test_deterministic_oram_get_branches_to_evict() {
This test seems to conflict with the description on `deterministic_get_next_branch_to_evict`.
> /// Selects branches in reverse lexicographic order. Num_bits_needed corresponds
/// to the number of possible branches that need to be explored. The iteration i
/// corresponds to the ith branch in reverse lexicographic order.

based on the description it would seem that the results should be `15, 14, 13, 12, 11, 10, 9, 8, 15`, not the `8, 12, 10, 14, 9, 13, 11, 15, 8` that is shown here.

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +    // calculation furtherdown that would overflow, and does not leak
:upside_down_face: 
```suggestion
    // calculation further down that would overflow, and does not leak
```

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +fn deterministic_get_next_branch_to_evict(num_bits_needed: u32, iteration: u64) -> u64 {
:thought_balloon: 
I'm thinking the `num_bits_needed` is breaking the abstraction unnecessarily.  
Would it make more sense for this to be `depth`?
This is for working on a binary tree, and the `depth` is the depth of the leaf nodes.  It happens that the depth also corresponds to the number of bits because a binary tree is log 2 n.

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +        ((iteration).reverse_bits() >> (64 - num_bits_needed)) % leaf_significant_index;
:x:  (Along with the comment in the tests) 
The description of this function and the test results don't seem to be in alignment.

If the desire is reverse lexicographical order and I'm understanding correctly, I think this should be:
```suggestion
    let test_position = !iteration % leaf_significant_index;
```

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +    tree_height: u32,
:x: Is this really `height`?  https://stackoverflow.com/a/2603707
Looking at the definitions of `TreeIndex::random_child_at_height` and `TreeIndex::height` this looks to be depth.  
I can understand that this wording inversion was here before, but that means an explanation should accompany every inversion of the term(s).

IFF I'm incorrect terminology, suggest a separate issue/PR be created to address it.  While I can understand "it works"TM, this wording will continue to be a maintenance burden and more likely to introduce errors or confusion longer term.

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +/// oram eviction strategy
:wrench: This wording seems off, not sure if it was meant to be something like
```suggestion
/// lexicographic order using the path oram eviction strategy
```

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +        self.branches_evicted = (self.branches_evicted + 1) % self.tree_size;
:x: tree size is the total number of nodes in the tree, https://en.wikipedia.org/wiki/Tree_%28data_structure%29#Terminology
> Size of a tree
    Number of nodes in the tree. 

this looks to be the `breadth`

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +        tree_size: u64,
:thought_balloon: based on usage it seems like the `tree_size` can be directly derived from the `tree_height`.  Would it be better to omit the `tree_size` from the `new()` method?

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +    fn create(&self, size: u64, height: u32) -> Self::Output;
:wrench: This is a public trait, should probably have documentation on `create` to document inputs and how they affect the output

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +    /// on.
:wrench: Suggest explicitly linking to the function
```suggestion
    /// Returns the leaf index of the next branch to call 
    /// [EvictionStrategy::evict_from_stash_to_branch] on.
    fn get_next_branch_to_evict(&mut self) -> u64;

    /// Returns the number of branches to call 
    /// [EvictionStrategy::evict_from_stash_to_branch] on.

```

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +pub trait EvictorCreator<ValueSize, Z>
:thought_balloon: If this is a "factory" should it be called that? `EvictorFactory`  or should the `Factory` be on the concrete type and not the trait?

It looks like there were previous `Creator` traits and structs so might be better to keep `Creator`

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +pub struct PathOramDeterministicEvictCreator {
:thought_balloon: Similar to above if this is a factor should it be named as such? `PathOramDeterministicEvictorFactory`

Also expanded `Evict` don't think this should truncate `Evictor` as it makes it harder to grep for.

Looks like there are other `Creator` traits and structs so might be better to maintain `Creator`

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/evictor/mod.rs
> +    /// number_of_additional_branches_to_evict branches per access
:upside_down_face: 
```suggestion
    /// `number_of_additional_branches_to_evict` branches per access
```

2022-08-22 16:23 UTC, nick-mobilecoin commented on mc-oblivious-ram/src/path_oram/mod.rs
> +        }
:question: 
I'm probably missing it, but this looks like new behavior that wasn't there before, and yet not really seeing any testing of this behavior.
It looks like currently the evictor is created with 0 additional branches.  
Is this the pre-emptive logic to handle evicting both sides of the root for circuit oram?

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +        ((iteration).reverse_bits() >> (64 - num_bits_needed)) % leaf_significant_index;
I tried adding clarification on the top level to explain the confusion here.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +    tree_height: u32,
I believe this is correct terminology. I don't think it is conventional to refer to tree depth, since tree height and depth should be equivalent, and at this level, there is no branch specific property that I'm asking for. I do agree that it might be confusing for me to be using height effectively as depth for selecting leaves. And I especially agree that "random child at height" could be misleading. I will do a separate PR addressing this. But this specific reference to tree_height does seem appropriate.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +/// oram eviction strategy
Agreed, sorry.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +        tree_size: u64,
I think you're right. I originally thought I required tree size because I required the number of elements, which can not be derived without the bucket size. But it seems like I should be able to use the tree breadth equivalently everywhere that it is currently being used and most places I should have access to bucket size anyway.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +        self.branches_evicted = (self.branches_evicted + 1) % self.tree_size;
Agree that this appears to be wrong here.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +    fn test_deterministic_oram_get_branches_to_evict() {
I can see how that might be misleading. It is reverse lexicographic on the number of non leaf significant bits. So here that is. 1000, 1100, 1010, 1110, 1001, 1101, 1011, 1111, 1000.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +fn deterministic_get_next_branch_to_evict(num_bits_needed: u32, iteration: u64) -> u64 {
I thought this was actually indicating that I'm trying to only reverse the bits specified in num_bits_needed rather than all of the bits in the reverse lexicographic ordering. I will rename to num_bits_to_be_reversed and maybe that would help?

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +    /// number_of_additional_branches_to_evict branches per access
Thanks

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +pub struct PathOramDeterministicEvictCreator {
For consistency, we should probably continue to use creator. Good call to rename Evict for easier grep.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +    fn create(&self, size: u64, height: u32) -> Self::Output;
Good call.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/evictor/mod.rs
> +mod internal_tests {
Done.

2022-09-02 17:24 UTC, wjuan-mob commented on mc-oblivious-ram/src/path_oram/mod.rs
> +        }
This is correct. This new behaviour isn't really exercised because path oram does not need to evict any additional branches, but it should be able to support it if desired.

2022-09-02 19:49 UTC, nick-mobilecoin approved these changes
LGTM, thanks!

2022-09-08 06:45 UTC, closed without merging

2022-09-08 06:46 UTC, wjuan-mob commented
Closing in order to repoint to different repo.